-- ============================================================================
-- Kairos knowledge base v1
-- Generated from scripts/generate_knowledge_base_v1.py
-- Core KB: 20 drivers, 50 causal arcs, 24 historical episodes, 280 asset rows
-- Kairos propagation attenuation standard: 0.6 per level
-- ============================================================================

BEGIN;

INSERT INTO drivers (driver_id, label_fr, label_en, category, unit, description)
VALUES
  ('taux_directeurs', 'Taux directeurs', 'Policy rates', 'monetary', '%', 'Niveau du taux directeur implicite pour la zone ou l''economie de reference.'),
  ('liquidite_globale', 'Liquidite globale', 'Global liquidity', 'financial', 'index', 'Conditions globales de bilan des banques centrales et abondance de liquidite en dollars.'),
  ('liquidite_bancaire', 'Liquidite bancaire', 'Bank liquidity', 'financial', 'index', 'Disponibilite de collateraux et de depots dans le systeme bancaire.'),
  ('conditions_credit', 'Conditions de credit', 'Credit conditions', 'credit', 'index', 'Tightening ou easing de l''offre de credit bancaire et de marche.'),
  ('spreads_credit', 'Spreads de credit', 'Credit spreads', 'credit', 'bps', 'Prime de risque demandee sur la dette corporate investment grade et high yield.'),
  ('spreads_souverains', 'Spreads souverains', 'Sovereign spreads', 'sovereign', 'bps', 'Prime de risque souveraine versus Bund ou Treasury de reference.'),
  ('inflation_headline', 'Inflation headline', 'Headline inflation', 'prices', '% yoy', 'Variation annuelle du CPI/IPC, incluant energie et alimentation.'),
  ('inflation_core', 'Inflation core', 'Core inflation', 'prices', '% yoy', 'Inflation sous-jacente hors composantes volatiles, plus utile pour la reaction des banques centrales.'),
  ('anticipations_inflation', 'Anticipations d''inflation', 'Inflation expectations', 'expectations', '%', 'Breakevens 5y5y et surveys de menages/entreprises sur l''inflation future.'),
  ('croissance_pib', 'Croissance PIB', 'GDP growth', 'growth', '% qoq', 'Impulsion de croissance reelle, proxifiee par PIB et nowcasts.'),
  ('emploi_chomage', 'Emploi / chomage', 'Labor market', 'growth', '%', 'Solidite du marche du travail via NFP, taux de chomage et job openings.'),
  ('investissement', 'Investissement', 'Investment', 'growth', '% gdp', 'FBCF privee et depenses capex cycliques.'),
  ('consommation', 'Consommation', 'Consumption', 'growth', '% gdp', 'Dynamique de demande finale des menages et resilience du revenu reel.'),
  ('usd_strength', 'Force du dollar', 'USD strength', 'fx', 'index', 'Direction du dollar global, captee via DXY et flux refuges.'),
  ('prix_petrole', 'Prix du petrole', 'Oil price', 'commodity', 'USD/bbl', 'Prix spot et futures du Brent/WTI comme choc energetique global.'),
  ('prix_metaux', 'Prix des metaux', 'Industrial metals prices', 'commodity', 'index', 'Prix du cuivre, aluminium et panier de metaux cycliques.'),
  ('sentiment_marche', 'Sentiment de marche', 'Market sentiment', 'market', 'index', 'Appetit pour le risque / aversion au risque, via VIX, credit et breadth.'),
  ('risque_geopolitique', 'Risque geopolitique', 'Geopolitical risk', 'market', 'index', 'Niveau de tension geopolitique a portee macro, militaire ou diplomatique.'),
  ('dette_publique', 'Dette publique', 'Public debt', 'fiscal', '% gdp', 'Charge et trajectoire de dette souveraine rapportee au PIB.'),
  ('balance_commerciale', 'Balance commerciale', 'Trade balance', 'trade', 'USD bn', 'Solde commercial et deterioration / amelioration des flux exterieurs.')
ON CONFLICT (driver_id) DO UPDATE SET
  label_fr = EXCLUDED.label_fr,
  label_en = EXCLUDED.label_en,
  category = EXCLUDED.category,
  unit = EXCLUDED.unit,
  description = EXCLUDED.description,
  active = TRUE;

INSERT INTO causal_arcs (
  arc_id, source_driver, target_driver, direction, intensity,
  intensity_coefficient, delay, conditions, confidence, notes
)
VALUES
  ('c253f7da-b8ae-5e27-a1a5-40244f14c7aa', 'taux_directeurs', 'conditions_credit', -1, 'strong', 0.820, '1-4w', '[]'::jsonb, 0.910, 'Rate hikes tighten bank lending standards with a short lag.'),
  ('1ac2ea5d-8bb3-5e57-89b0-eb73cd11cb64', 'taux_directeurs', 'liquidite_globale', -1, 'strong', 0.740, '1-4w', '[]'::jsonb, 0.880, 'Balance sheet tightening and higher policy rates drain global dollar liquidity.'),
  ('58d3cbc4-3dee-57a9-b8f7-0f49b48f6bdd', 'taux_directeurs', 'spreads_credit', 1, 'moderate', 0.630, '1-4w', '[]'::jsonb, 0.860, 'Higher discount rates lift refinancing stress for corporate issuers.'),
  ('0045ce6f-0d46-5a0d-932d-9255e65b5c7c', 'taux_directeurs', 'usd_strength', 1, 'moderate', 0.580, 'immediate', '[]'::jsonb, 0.840, 'Rate differentials support USD through carry and safe-rate demand.'),
  ('47e0a36b-057e-5eb0-a39c-5679960f82fe', 'taux_directeurs', 'croissance_pib', -1, 'moderate', 0.460, '1-6m', '[]'::jsonb, 0.770, 'Tighter policy slows activity with a several-quarter lag.'),
  ('283ba451-f451-5d2e-ba3b-573c2985e7fc', 'taux_directeurs', 'inflation_headline', -1, 'low', 0.280, '1-6m', '[]'::jsonb, 0.720, 'Disinflation works with a lag via demand destruction and financing costs.'),
  ('bf4ddaa9-c6d4-52cb-a27c-72b2ac49caef', 'taux_directeurs', 'investissement', -1, 'moderate', 0.550, '1-6m', '[]'::jsonb, 0.810, 'Capex is rate-sensitive through hurdle rates and credit availability.'),
  ('294e7d73-be91-5693-8b2c-eba2fb96af5b', 'liquidite_globale', 'spreads_souverains', -1, 'strong', 0.760, '1-4w', '[]'::jsonb, 0.890, 'QE-style liquidity compresses sovereign term premia and spreads.'),
  ('098f8e55-dcc0-52aa-b7b9-ab6425b3a348', 'liquidite_globale', 'conditions_credit', 1, 'strong', 0.780, '1-4w', '[]'::jsonb, 0.880, 'Abundant reserves and funding conditions ease bank credit creation.'),
  ('e0f117b3-b88f-5fac-acd5-df988fc4dd4d', 'liquidite_globale', 'sentiment_marche', 1, 'moderate', 0.520, 'immediate', '[]'::jsonb, 0.800, 'Liquidity support improves cross-asset risk appetite.'),
  ('ebae0bb5-6dff-508b-a7be-69e3ed2185ba', 'liquidite_globale', 'usd_strength', -1, 'moderate', 0.440, '1-4w', '[]'::jsonb, 0.760, 'Dollar liquidity expansion tends to soften the broad USD.'),
  ('ee1a741a-2871-58a4-9458-fb6c3c11b916', 'liquidite_bancaire', 'conditions_credit', 1, 'strong', 0.810, 'immediate', '[]'::jsonb, 0.870, 'Banks with better liquidity buffers lend more readily.'),
  ('313f5b85-7658-5b45-8fb9-b1d0000bc45e', 'liquidite_bancaire', 'spreads_credit', -1, 'moderate', 0.590, 'immediate', '[]'::jsonb, 0.790, 'Funding stress relief narrows corporate spread compensation.'),
  ('0e1c1180-a3d1-5f3f-8382-40c058c5513d', 'conditions_credit', 'investissement', 1, 'strong', 0.720, '1-6m', '[]'::jsonb, 0.880, 'Easier bank lending transmits directly into capex.'),
  ('6e07bd67-fa1a-5563-aef1-1dda361ab26c', 'conditions_credit', 'consommation', 1, 'moderate', 0.470, '1-6m', '[]'::jsonb, 0.760, 'Consumer credit availability lifts durable goods demand.'),
  ('0488f1fb-2d74-53c8-b0f4-d4a2f69829bb', 'conditions_credit', 'croissance_pib', 1, 'strong', 0.680, '1-6m', '[]'::jsonb, 0.860, 'Broad easing in credit conditions supports aggregate demand.'),
  ('0bf0e97c-6564-5bc8-abbb-683aa495cf73', 'conditions_credit', 'spreads_credit', -1, 'moderate', 0.510, '1-4w', '[]'::jsonb, 0.780, 'Looser financing conditions compress IG/HY spreads.'),
  ('7c833b05-cf05-5c82-a744-ed36eabb7802', 'spreads_credit', 'croissance_pib', -1, 'moderate', 0.590, '1-6m', '[]'::jsonb, 0.830, 'Wider spreads precede weaker investment and activity.'),
  ('1ba0b530-aa42-5b84-806e-25f278fd0d79', 'spreads_credit', 'sentiment_marche', -1, 'moderate', 0.530, 'immediate', '[]'::jsonb, 0.820, 'Credit stress quickly deteriorates risk sentiment.'),
  ('d72394e6-02a5-58ae-a245-97ab373331eb', 'spreads_souverains', 'conditions_credit', -1, 'moderate', 0.420, '1-4w', '[]'::jsonb, 0.740, 'Sovereign stress bleeds into domestic bank balance sheets and lending.'),
  ('d7d328ef-1fec-5f96-9ba8-dfcdc7b4f594', 'spreads_souverains', 'dette_publique', 1, 'low', 0.340, '1-6m', '[]'::jsonb, 0.710, 'Higher sovereign funding costs worsen debt-service dynamics.'),
  ('0b97922d-7dba-5b78-865e-58340a9e3e36', 'inflation_headline', 'anticipations_inflation', 1, 'strong', 0.740, '1-4w', '[]'::jsonb, 0.870, 'Repeated upside CPI prints re-anchor medium-term expectations higher.'),
  ('7317d943-bc85-5cec-9261-37408d296d74', 'inflation_headline', 'taux_directeurs', 1, 'strong', 0.690, '1-4w', '[{"driver":"inflation_headline","operator":">","threshold":3.0}]'::jsonb, 0.880, 'Central banks react faster when headline inflation breaches comfort zones.'),
  ('fe39202f-e7e5-50fd-b478-61b0bef92808', 'inflation_headline', 'consommation', -1, 'moderate', 0.360, '1-4w', '[]'::jsonb, 0.730, 'Real income compression weighs on household demand.'),
  ('fa1515a3-c819-5db5-8b7a-2abf274449c9', 'inflation_headline', 'usd_strength', 1, 'low', 0.270, 'immediate', '[{"driver":"taux_directeurs","operator":">=","threshold":3.0}]'::jsonb, 0.680, 'Inflation surprises can support USD via hawkish repricing.'),
  ('02b51736-53cc-50c2-abce-c74594d0b7c6', 'inflation_core', 'taux_directeurs', 1, 'strong', 0.770, '1-4w', '[{"driver":"inflation_core","operator":">","threshold":2.5}]'::jsonb, 0.900, 'Persistent core inflation is the most reliable trigger for policy tightening.'),
  ('f58d7d19-cc69-5702-9260-ed2e3b33e813', 'inflation_core', 'anticipations_inflation', 1, 'moderate', 0.610, '1-4w', '[]'::jsonb, 0.800, 'Sticky core services inflation shapes medium-term inflation expectations.'),
  ('f29b6c01-47c3-5831-b6ad-898e53819a3d', 'anticipations_inflation', 'taux_directeurs', 1, 'moderate', 0.620, '1-4w', '[]'::jsonb, 0.810, 'Breakeven drift higher tightens reaction functions.'),
  ('3022aeaa-004a-5e76-b4b0-45c753b3b3b2', 'anticipations_inflation', 'spreads_souverains', 1, 'moderate', 0.490, 'immediate', '[]'::jsonb, 0.760, 'Higher inflation expectations raise nominal term premia.'),
  ('e78f8acc-def5-557c-af10-e1b1e62c684f', 'croissance_pib', 'emploi_chomage', -1, 'strong', 0.710, '1-6m', '[]'::jsonb, 0.880, 'Stronger real activity reduces unemployment with a lag.'),
  ('badbf16f-124f-5ac6-b11a-a73e991d19bf', 'croissance_pib', 'consommation', 1, 'strong', 0.660, '1-6m', '[]'::jsonb, 0.820, 'Growth improves income confidence and spending capacity.'),
  ('b8b4bb89-bb20-5bf4-908f-57843a24f450', 'croissance_pib', 'investissement', 1, 'strong', 0.740, '1-6m', '[]'::jsonb, 0.870, 'Output growth raises capacity utilisation and capex demand.'),
  ('29103714-fe87-542b-9d1c-43a38054aa94', 'croissance_pib', 'balance_commerciale', -1, 'low', 0.290, '1-6m', '[]'::jsonb, 0.650, 'Domestic-demand booms often widen import-driven trade deficits.'),
  ('4a2c1304-1ee8-5659-aa19-abad564128c6', 'emploi_chomage', 'consommation', -1, 'strong', 0.690, '1-4w', '[]'::jsonb, 0.840, 'Rising unemployment weakens household confidence and spending.'),
  ('6076db4e-1856-5e6f-a3e0-7fe39d16b438', 'investissement', 'croissance_pib', 1, 'strong', 0.720, '1-6m', '[]'::jsonb, 0.840, 'Capex feeds directly into GDP through domestic demand and productivity.'),
  ('97c17bde-c0f2-501d-a183-034dfa04505e', 'consommation', 'inflation_core', 1, 'moderate', 0.410, '1-6m', '[]'::jsonb, 0.740, 'Demand resilience sustains services inflation.'),
  ('ea8f3c86-a1a7-5885-b735-33cf65d077ed', 'usd_strength', 'inflation_headline', -1, 'moderate', 0.390, '1-6m', '[]'::jsonb, 0.730, 'A stronger dollar dampens imported inflation.'),
  ('03b9fa39-1d23-5cae-9a11-b4107b89699c', 'usd_strength', 'balance_commerciale', -1, 'moderate', 0.330, '1-6m', '[]'::jsonb, 0.690, 'Dollar strength reduces export competitiveness and widens trade deficits.'),
  ('a3f50883-dea5-5336-95f4-1708d2456326', 'usd_strength', 'prix_metaux', -1, 'moderate', 0.450, 'immediate', '[]'::jsonb, 0.770, 'Commodity prices often soften when USD funding tightens.'),
  ('e8dd44c9-34c9-5384-80e0-0e3c4d08f23a', 'prix_petrole', 'inflation_headline', 1, 'strong', 0.830, '1-4w', '[]'::jsonb, 0.920, 'Oil shocks pass rapidly into CPI through fuel and transport.'),
  ('53b1c9e0-f2f9-546d-b8f7-3b759e77077f', 'prix_petrole', 'croissance_pib', -1, 'moderate', 0.440, '1-6m', '[]'::jsonb, 0.800, 'Energy taxation on consumers and firms slows growth.'),
  ('77bd0e4b-545f-5e13-8378-31270af88f32', 'prix_petrole', 'balance_commerciale', -1, 'moderate', 0.520, '1-4w', '[]'::jsonb, 0.780, 'Energy-importing economies see trade balances deteriorate when oil rises.'),
  ('9537f3bf-8684-5fce-994c-e5936f06ce9e', 'prix_metaux', 'inflation_core', 1, 'low', 0.260, '1-4w', '[]'::jsonb, 0.670, 'Input-cost pressure from metals can leak into core goods inflation.'),
  ('895db623-65ed-5454-894b-450ddf17882f', 'risque_geopolitique', 'prix_petrole', 1, 'strong', 0.880, 'immediate', '[]'::jsonb, 0.930, 'Conflict near energy routes causes immediate crude risk premia.'),
  ('53901071-89a2-5d8d-8d25-add49727de45', 'risque_geopolitique', 'sentiment_marche', -1, 'strong', 0.810, 'immediate', '[]'::jsonb, 0.910, 'Geopolitical escalation drives fast risk-off positioning.'),
  ('eab594f3-b779-54ba-8cab-742132c2cee1', 'risque_geopolitique', 'usd_strength', 1, 'strong', 0.730, 'immediate', '[]'::jsonb, 0.860, 'Safe-haven flows lift the USD during geopolitical stress.'),
  ('14e9560a-0d00-532b-a709-79efec48f6cd', 'risque_geopolitique', 'balance_commerciale', -1, 'moderate', 0.410, '1-4w', '[]'::jsonb, 0.740, 'Sanctions and route disruptions impair external trade flows.'),
  ('81202124-21ce-53d7-b741-f183f38b7bf8', 'sentiment_marche', 'spreads_credit', -1, 'strong', 0.670, 'immediate', '[]'::jsonb, 0.870, 'Improving sentiment narrows corporate risk premia.'),
  ('7e93801c-6215-56cd-bd65-93266e4e4b74', 'dette_publique', 'spreads_souverains', 1, 'strong', 0.720, '1-6m', '[{"driver":"dette_publique","operator":">","threshold":90.0}]'::jsonb, 0.840, 'Debt sustainability concerns widen sovereign spreads once debt ratios become elevated.'),
  ('cfb66d02-b8fe-53db-b811-9edb9235c864', 'balance_commerciale', 'usd_strength', 1, 'moderate', 0.360, '1-6m', '[]'::jsonb, 0.700, 'Persistent external surpluses support currency strength over time.')
ON CONFLICT (source_driver, target_driver) DO UPDATE SET
  arc_id = EXCLUDED.arc_id,
  direction = EXCLUDED.direction,
  intensity = EXCLUDED.intensity,
  intensity_coefficient = EXCLUDED.intensity_coefficient,
  delay = EXCLUDED.delay,
  conditions = EXCLUDED.conditions,
  confidence = EXCLUDED.confidence,
  notes = EXCLUDED.notes,
  active = TRUE,
  last_calibrated = NOW(),
  updated_at = NOW();

INSERT INTO historical_episodes (
  episode_id, cat_id, subtype_id, episode_date, label, geography,
  driver_impacts, asset_outcomes, notes, data_quality
)
VALUES
  ('c5e116e8-b89e-5f5c-9eb9-e026ce1c4f18', 'CAT-01', 'emergency_action_tightening', '1979-10-06', 'Volcker shock tightening', ARRAY['US'], '{"taux_directeurs":{"direction":1,"magnitude":0.935,"delay_days":0},"liquidite_globale":{"direction":-1,"magnitude":0.66,"delay_days":0},"spreads_souverains":{"direction":-1,"magnitude":0.442,"delay_days":0},"conditions_credit":{"direction":-1,"magnitude":0.935,"delay_days":14}}'::jsonb, '{"bonds_sovereign_us":{"direction":-1,"change_pct":-2.6,"horizon_days":10},"equities_us_growth":{"direction":-1,"change_pct":-4.3,"horizon_days":20},"usd_dxy":{"direction":1,"change_pct":1.9,"horizon_days":10},"gold":{"direction":-1,"change_pct":-1.8,"horizon_days":10}}'::jsonb, 'Policy shock can dominate recession fears in the first phase. | Cross-asset reaction is strongest when inflation credibility is broken.', 'medium'),
  ('17542cf6-1120-58c2-aefa-70d3fb94931c', 'CAT-01', 'rate_decision_hike', '2011-04-07', 'ECB rate hike into sovereign stress', ARRAY['EZ'], '{"taux_directeurs":{"direction":1,"magnitude":0.9,"delay_days":0},"conditions_credit":{"direction":-1,"magnitude":0.9,"delay_days":14},"liquidite_globale":{"direction":-1,"magnitude":0.603,"delay_days":14},"spreads_credit":{"direction":1,"magnitude":0.603,"delay_days":14},"usd_strength":{"direction":1,"magnitude":0.603,"delay_days":0},"anticipations_inflation":{"direction":-1,"magnitude":0.603,"delay_days":14}}'::jsonb, '{"bonds_sovereign_us":{"direction":-1,"change_pct":-2.6,"horizon_days":10},"equities_us_growth":{"direction":-1,"change_pct":-4.3,"horizon_days":20},"usd_dxy":{"direction":1,"change_pct":1.9,"horizon_days":10},"gold":{"direction":-1,"change_pct":-1.8,"horizon_days":10}}'::jsonb, 'Late-cycle hikes amplify sovereign and bank fragility. | EUR support is short-lived when credit transmission breaks.', 'high'),
  ('a13dd3cd-0703-5493-b6ae-508b9ddc00f4', 'CAT-01', 'qe_announcement', '2009-03-18', 'Fed QE1 expansion', ARRAY['US'], '{"liquidite_globale":{"direction":1,"magnitude":0.9,"delay_days":0},"taux_directeurs":{"direction":-1,"magnitude":0.6,"delay_days":0},"spreads_souverains":{"direction":-1,"magnitude":0.9,"delay_days":14},"conditions_credit":{"direction":1,"magnitude":0.9,"delay_days":14},"spreads_credit":{"direction":-1,"magnitude":0.603,"delay_days":14},"usd_strength":{"direction":-1,"magnitude":0.603,"delay_days":14}}'::jsonb, '{"bonds_sovereign_us":{"direction":1,"change_pct":2.1,"horizon_days":10},"equities_us_growth":{"direction":1,"change_pct":5.0,"horizon_days":20},"usd_dxy":{"direction":-1,"change_pct":-1.4,"horizon_days":10},"gold":{"direction":1,"change_pct":2.7,"horizon_days":20}}'::jsonb, 'Balance-sheet policy compresses sovereign and credit premia quickly. | USD weakness and gold strength are common first-order effects.', 'high'),
  ('a8d14835-ceb5-54e0-ab4d-401a113efd25', 'CAT-01', 'tapering', '2013-05-22', 'Taper Tantrum signal', ARRAY['US', 'GLOBAL'], '{"liquidite_globale":{"direction":-1,"magnitude":0.578,"delay_days":0},"spreads_souverains":{"direction":1,"magnitude":0.252,"delay_days":14},"taux_directeurs":{"direction":1,"magnitude":0.252,"delay_days":90}}'::jsonb, '{"bonds_sovereign_us":{"direction":-1,"change_pct":-2.6,"horizon_days":10},"equities_us_growth":{"direction":-1,"change_pct":-4.3,"horizon_days":20},"usd_dxy":{"direction":1,"change_pct":1.9,"horizon_days":10},"gold":{"direction":-1,"change_pct":-1.8,"horizon_days":10}}'::jsonb, 'Unexpected liquidity withdrawal shocks EM FX before growth data move. | Communication surprise matters more than the first mechanical flow reduction.', 'high'),
  ('6748314c-67a6-5130-a47c-8b15b6112176', 'CAT-01', 'rate_decision_hike', '2022-03-16', 'Fed liftoff inflation cycle', ARRAY['US', 'GLOBAL'], '{"taux_directeurs":{"direction":1,"magnitude":0.9,"delay_days":0},"conditions_credit":{"direction":-1,"magnitude":0.9,"delay_days":14},"liquidite_globale":{"direction":-1,"magnitude":0.603,"delay_days":14},"spreads_credit":{"direction":1,"magnitude":0.603,"delay_days":14},"usd_strength":{"direction":1,"magnitude":0.603,"delay_days":0},"anticipations_inflation":{"direction":-1,"magnitude":0.603,"delay_days":14}}'::jsonb, '{"bonds_sovereign_us":{"direction":-1,"change_pct":-2.6,"horizon_days":10},"equities_us_growth":{"direction":-1,"change_pct":-4.3,"horizon_days":20},"usd_dxy":{"direction":1,"change_pct":1.9,"horizon_days":10},"gold":{"direction":-1,"change_pct":-1.8,"horizon_days":10}}'::jsonb, 'Rate hikes transmit fastest through duration and USD. | Credit and growth damage builds with a lag, not on day one.', 'high'),
  ('55d9e0d6-c240-567c-b141-3b8c71c3722e', 'CAT-02', 'inflation_cpi_above', '2022-06-10', 'US CPI upside shock', ARRAY['US'], '{"inflation_headline":{"direction":1,"magnitude":0.98,"delay_days":0},"anticipations_inflation":{"direction":1,"magnitude":0.77,"delay_days":0},"taux_directeurs":{"direction":1,"magnitude":0.663,"delay_days":14},"spreads_souverains":{"direction":1,"magnitude":0.516,"delay_days":0},"conditions_credit":{"direction":-1,"magnitude":0.264,"delay_days":14}}'::jsonb, '{"bonds_sovereign_us":{"direction":-1,"change_pct":-1.8,"horizon_days":3},"bonds_inflation_linked":{"direction":1,"change_pct":0.9,"horizon_days":5},"equities_us_growth":{"direction":-1,"change_pct":-3.1,"horizon_days":5},"usd_dxy":{"direction":1,"change_pct":0.8,"horizon_days":3}}'::jsonb, 'Inflation surprises can reroute the entire rates path in a single session. | Growth equities underperform before credit does.', 'high'),
  ('9ff55861-4c5a-5633-a392-de39b6c67ae8', 'CAT-02', 'pmi_contraction', '2020-03-24', 'Pandemic PMI collapse', ARRAY['GLOBAL'], '{"croissance_pib":{"direction":-1,"magnitude":0.747,"delay_days":0},"investissement":{"direction":-1,"magnitude":0.632,"delay_days":0},"sentiment_marche":{"direction":-1,"magnitude":0.462,"delay_days":0},"emploi_chomage":{"direction":1,"magnitude":0.276,"delay_days":14}}'::jsonb, '{"bonds_sovereign_us":{"direction":1,"change_pct":1.6,"horizon_days":5},"equities_us_growth":{"direction":-1,"change_pct":-4.8,"horizon_days":10},"oil_wti":{"direction":-1,"change_pct":-6.5,"horizon_days":10},"metals_industrial":{"direction":-1,"change_pct":-5.2,"horizon_days":10}}'::jsonb, 'PMI contractions are powerful early warnings for capex and trade weakness. | Market pricing moves ahead of GDP releases.', 'high'),
  ('66b7fc42-5637-56cc-be2c-7cd22901e555', 'CAT-02', 'nfp_below', '2020-04-03', 'US payrolls collapse', ARRAY['US'], '{"emploi_chomage":{"direction":1,"magnitude":0.98,"delay_days":0},"consommation":{"direction":-1,"magnitude":0.75,"delay_days":7},"taux_directeurs":{"direction":-1,"magnitude":0.684,"delay_days":14},"croissance_pib":{"direction":-1,"magnitude":0.24,"delay_days":90}}'::jsonb, '{"bonds_sovereign_us":{"direction":1,"change_pct":1.6,"horizon_days":5},"equities_us_growth":{"direction":-1,"change_pct":-4.8,"horizon_days":10},"oil_wti":{"direction":-1,"change_pct":-6.5,"horizon_days":10},"metals_industrial":{"direction":-1,"change_pct":-5.2,"horizon_days":10}}'::jsonb, 'Labor shocks hit consumption immediately even when policy support follows. | Bond rally is strongest when payroll weakness coincides with falling oil.', 'high'),
  ('cdef0913-69d9-55b0-9678-bd6862c71fe6', 'CAT-03', 'armed_conflict_start', '1990-08-02', 'Iraq invades Kuwait', ARRAY['MIDDLE_EAST', 'GLOBAL'], '{"risque_geopolitique":{"direction":1,"magnitude":0.95,"delay_days":0},"sentiment_marche":{"direction":-1,"magnitude":0.85,"delay_days":0},"prix_petrole":{"direction":1,"magnitude":0.95,"delay_days":0},"prix_metaux":{"direction":1,"magnitude":0.636,"delay_days":0},"liquidite_globale":{"direction":-1,"magnitude":0.636,"delay_days":0},"usd_strength":{"direction":1,"magnitude":0.95,"delay_days":0},"spreads_souverains":{"direction":1,"magnitude":0.95,"delay_days":14}}'::jsonb, '{"gold":{"direction":1,"change_pct":3.4,"horizon_days":5},"oil_wti":{"direction":1,"change_pct":7.8,"horizon_days":5},"usd_dxy":{"direction":1,"change_pct":1.2,"horizon_days":5},"equities_em":{"direction":-1,"change_pct":-5.5,"horizon_days":10}}'::jsonb, 'Oil and gold react immediately to military escalation near supply routes. | Safe-haven dollar demand can coexist with weaker global growth expectations.', 'medium'),
  ('c00e5a83-a948-583e-a0e1-4bf0c9d8f5ee', 'CAT-03', 'armed_conflict_start', '2022-02-24', 'Russia invades Ukraine', ARRAY['EUROPE', 'GLOBAL'], '{"risque_geopolitique":{"direction":1,"magnitude":0.98,"delay_days":0},"sentiment_marche":{"direction":-1,"magnitude":0.935,"delay_days":0},"prix_petrole":{"direction":1,"magnitude":0.98,"delay_days":0},"prix_metaux":{"direction":1,"magnitude":0.7,"delay_days":0},"liquidite_globale":{"direction":-1,"magnitude":0.7,"delay_days":0},"usd_strength":{"direction":1,"magnitude":0.98,"delay_days":0},"spreads_souverains":{"direction":1,"magnitude":0.98,"delay_days":14}}'::jsonb, '{"gold":{"direction":1,"change_pct":3.4,"horizon_days":5},"oil_wti":{"direction":1,"change_pct":7.8,"horizon_days":5},"usd_dxy":{"direction":1,"change_pct":1.2,"horizon_days":5},"equities_em":{"direction":-1,"change_pct":-5.5,"horizon_days":10}}'::jsonb, 'Europe transmits geopolitical energy shocks faster than the US. | Gas, FX and sovereign spread channels matter alongside crude.', 'high'),
  ('28919111-bd45-591a-b684-1e0cbd4ceb44', 'CAT-03', 'sanctions_announcement', '2018-11-05', 'US restores Iran oil sanctions', ARRAY['US', 'MIDDLE_EAST', 'GLOBAL'], '{"balance_commerciale":{"direction":-1,"magnitude":0.7,"delay_days":0},"prix_petrole":{"direction":1,"magnitude":0.6,"delay_days":0},"usd_strength":{"direction":1,"magnitude":0.402,"delay_days":0},"spreads_souverains":{"direction":1,"magnitude":0.6,"delay_days":0},"risque_geopolitique":{"direction":1,"magnitude":0.402,"delay_days":0}}'::jsonb, '{"gold":{"direction":1,"change_pct":3.4,"horizon_days":5},"oil_wti":{"direction":1,"change_pct":7.8,"horizon_days":5},"usd_dxy":{"direction":1,"change_pct":1.2,"horizon_days":5},"equities_em":{"direction":-1,"change_pct":-5.5,"horizon_days":10}}'::jsonb, 'Sanctions shocks move trade balances and oil before they move GDP. | USD and sovereign spreads are key spillover channels.', 'high'),
  ('1c15045e-ead8-5c0b-8eb8-2fa10cfd340f', 'CAT-04', 'oil_supply_disruption', '1973-10-17', 'Arab oil embargo', ARRAY['MIDDLE_EAST', 'GLOBAL'], '{"prix_petrole":{"direction":1,"magnitude":0.98,"delay_days":0},"inflation_headline":{"direction":1,"magnitude":0.98,"delay_days":14},"prix_metaux":{"direction":1,"magnitude":0.414,"delay_days":14},"sentiment_marche":{"direction":-1,"magnitude":0.462,"delay_days":0}}'::jsonb, '{"oil_wti":{"direction":1,"change_pct":12.0,"horizon_days":20},"bonds_inflation_linked":{"direction":1,"change_pct":1.7,"horizon_days":20},"equities_energy":{"direction":1,"change_pct":6.8,"horizon_days":20},"bonds_sovereign_us":{"direction":-1,"change_pct":-1.1,"horizon_days":20}}'::jsonb, 'Supply shocks generate persistent headline inflation and growth drag. | Energy equities hedge the first-round inflation impulse better than broad equities.', 'medium'),
  ('38c9d9cd-7004-5c8d-99ef-75cbb1e0164d', 'CAT-04', 'opec_cut', '2022-10-05', 'OPEC+ production cut', ARRAY['GLOBAL'], '{"prix_petrole":{"direction":1,"magnitude":0.9,"delay_days":0},"inflation_headline":{"direction":1,"magnitude":0.603,"delay_days":14},"anticipations_inflation":{"direction":1,"magnitude":0.402,"delay_days":14},"taux_directeurs":{"direction":1,"magnitude":0.24,"delay_days":14},"balance_commerciale":{"direction":-1,"magnitude":0.36,"delay_days":90}}'::jsonb, '{"oil_wti":{"direction":1,"change_pct":12.0,"horizon_days":20},"bonds_inflation_linked":{"direction":1,"change_pct":1.7,"horizon_days":20},"equities_energy":{"direction":1,"change_pct":6.8,"horizon_days":20},"bonds_sovereign_us":{"direction":-1,"change_pct":-1.1,"horizon_days":20}}'::jsonb, 'Quota cuts reprice energy inflation quickly even without immediate physical scarcity. | Market positioning changes the second-round rates move.', 'high'),
  ('8289c9d1-3ecc-588d-84fa-f4f11f809e76', 'CAT-04', 'gas_supply_disruption', '2022-09-02', 'Nord Stream halt and EU gas panic', ARRAY['EZ', 'GLOBAL'], '{"inflation_headline":{"direction":1,"magnitude":0.88,"delay_days":7},"croissance_pib":{"direction":-1,"magnitude":0.58,"delay_days":60},"anticipations_inflation":{"direction":1,"magnitude":0.442,"delay_days":14},"taux_directeurs":{"direction":1,"magnitude":0.264,"delay_days":14},"prix_petrole":{"direction":1,"magnitude":0.42,"delay_days":7}}'::jsonb, '{"oil_wti":{"direction":1,"change_pct":12.0,"horizon_days":20},"bonds_inflation_linked":{"direction":1,"change_pct":1.7,"horizon_days":20},"equities_energy":{"direction":1,"change_pct":6.8,"horizon_days":20},"bonds_sovereign_us":{"direction":-1,"change_pct":-1.1,"horizon_days":20}}'::jsonb, 'Regional gas shocks can overwhelm local macro despite limited direct US impact. | Utilities and sovereign curves diverge from US assets in Europe-specific crises.', 'high'),
  ('0a318b79-fcb4-524d-a401-6d253d48c841', 'CAT-05', 'trade_war_escalation', '2018-07-06', 'US-China tariff round', ARRAY['US', 'CN', 'GLOBAL'], '{"sentiment_marche":{"direction":-1,"magnitude":0.8,"delay_days":0},"balance_commerciale":{"direction":-1,"magnitude":0.65,"delay_days":0},"croissance_pib":{"direction":-1,"magnitude":0.402,"delay_days":90},"investissement":{"direction":-1,"magnitude":0.402,"delay_days":90},"conditions_credit":{"direction":-1,"magnitude":0.24,"delay_days":14}}'::jsonb, '{"equities_em":{"direction":-1,"change_pct":-4.7,"horizon_days":20},"usd_dxy":{"direction":1,"change_pct":1.1,"horizon_days":10},"metals_industrial":{"direction":-1,"change_pct":-4.2,"horizon_days":20},"bonds_sovereign_us":{"direction":1,"change_pct":1.0,"horizon_days":10}}'::jsonb, 'Trade policy shocks hit confidence and capex before official trade data roll over. | EM FX and industrial metals are efficient fast indicators.', 'high'),
  ('d1b91c86-03bd-598a-bebe-2a08f1e615be', 'CAT-05', 'trade_war_deescalation', '2020-01-15', 'US-China phase one truce', ARRAY['US', 'CN', 'GLOBAL'], '{"sentiment_marche":{"direction":1,"magnitude":0.7,"delay_days":0},"balance_commerciale":{"direction":1,"magnitude":0.4,"delay_days":0},"croissance_pib":{"direction":1,"magnitude":0.24,"delay_days":90},"investissement":{"direction":1,"magnitude":0.402,"delay_days":90}}'::jsonb, '{"equities_em":{"direction":1,"change_pct":3.8,"horizon_days":20},"usd_dxy":{"direction":-1,"change_pct":-0.7,"horizon_days":10},"metals_industrial":{"direction":1,"change_pct":3.0,"horizon_days":20},"bonds_hy":{"direction":1,"change_pct":1.2,"horizon_days":20}}'::jsonb, 'Trade relief improves cyclical beta more than long duration assets. | FX relief is stronger in EM than in EUR crosses.', 'high'),
  ('23d54e52-04bf-58bd-b930-03803feb5216', 'CAT-06', 'debt_ceiling_crisis', '2011-08-05', 'US debt ceiling and S&P downgrade', ARRAY['US', 'GLOBAL'], '{"spreads_souverains":{"direction":1,"magnitude":0.935,"delay_days":0},"sentiment_marche":{"direction":-1,"magnitude":0.88,"delay_days":0},"liquidite_globale":{"direction":-1,"magnitude":0.442,"delay_days":0},"usd_strength":{"direction":-1,"magnitude":0.442,"delay_days":0},"dette_publique":{"direction":1,"magnitude":0.264,"delay_days":14}}'::jsonb, '{"bonds_sovereign_ez":{"direction":-1,"change_pct":-2.7,"horizon_days":10},"equities_banks":{"direction":-1,"change_pct":-6.2,"horizon_days":10},"usd_dxy":{"direction":1,"change_pct":1.0,"horizon_days":10},"gold":{"direction":1,"change_pct":1.9,"horizon_days":10}}'::jsonb, 'Political fiscal brinkmanship widens sovereign premia and damages sentiment. | USD safe-haven behaviour can offset domestic fiscal stress in the short run.', 'high'),
  ('fa2325e8-4166-5a99-8f86-acba20a6a787', 'CAT-06', 'fiscal_stimulus_major', '2021-03-11', 'American Rescue Plan', ARRAY['US'], '{"croissance_pib":{"direction":1,"magnitude":0.85,"delay_days":0},"dette_publique":{"direction":1,"magnitude":0.65,"delay_days":0},"inflation_headline":{"direction":1,"magnitude":0.57,"delay_days":90},"taux_directeurs":{"direction":1,"magnitude":0.24,"delay_days":90},"spreads_souverains":{"direction":1,"magnitude":0.436,"delay_days":14},"emploi_chomage":{"direction":-1,"magnitude":0.402,"delay_days":90}}'::jsonb, '{"equities_us_value":{"direction":1,"change_pct":4.4,"horizon_days":20},"equities_banks":{"direction":1,"change_pct":5.1,"horizon_days":20},"bonds_sovereign_us":{"direction":-1,"change_pct":-1.4,"horizon_days":20},"oil_wti":{"direction":1,"change_pct":4.0,"horizon_days":20}}'::jsonb, 'Large fiscal stimulus lifts growth, inflation and debt simultaneously. | Banks and value equities outperform when nominal growth rises.', 'high'),
  ('11a67ec7-eecb-5d16-9771-fd6f76d912f2', 'CAT-07', 'bank_failure', '2008-09-15', 'Lehman bankruptcy', ARRAY['US', 'GLOBAL'], '{"liquidite_bancaire":{"direction":-1,"magnitude":0.98,"delay_days":0},"sentiment_marche":{"direction":-1,"magnitude":0.98,"delay_days":0},"conditions_credit":{"direction":-1,"magnitude":0.98,"delay_days":0},"spreads_credit":{"direction":1,"magnitude":0.72,"delay_days":0},"liquidite_globale":{"direction":-1,"magnitude":0.72,"delay_days":0},"croissance_pib":{"direction":-1,"magnitude":0.482,"delay_days":90}}'::jsonb, '{"bonds_sovereign_us":{"direction":1,"change_pct":2.4,"horizon_days":5},"equities_banks":{"direction":-1,"change_pct":-12.0,"horizon_days":5},"bonds_hy":{"direction":-1,"change_pct":-3.2,"horizon_days":10},"gold":{"direction":1,"change_pct":2.5,"horizon_days":10}}'::jsonb, 'Bank failures propagate instantly via liquidity, credit and confidence. | Credit spreads and bank equities are the fastest stress barometers.', 'high'),
  ('08bb94fd-f56d-5c31-9256-617fa15d42fc', 'CAT-07', 'bank_failure', '2023-03-10', 'Silicon Valley Bank collapse', ARRAY['US'], '{"liquidite_bancaire":{"direction":-1,"magnitude":0.9,"delay_days":0},"sentiment_marche":{"direction":-1,"magnitude":0.85,"delay_days":0},"conditions_credit":{"direction":-1,"magnitude":0.9,"delay_days":0},"spreads_credit":{"direction":1,"magnitude":0.6,"delay_days":0},"liquidite_globale":{"direction":-1,"magnitude":0.6,"delay_days":0},"croissance_pib":{"direction":-1,"magnitude":0.402,"delay_days":90},"taux_directeurs":{"direction":-1,"magnitude":0.32,"delay_days":7}}'::jsonb, '{"bonds_sovereign_us":{"direction":1,"change_pct":2.4,"horizon_days":5},"equities_banks":{"direction":-1,"change_pct":-12.0,"horizon_days":5},"bonds_hy":{"direction":-1,"change_pct":-3.2,"horizon_days":10},"gold":{"direction":1,"change_pct":2.5,"horizon_days":10}}'::jsonb, 'Duration losses can morph into liquidity crises even without immediate credit losses. | Front-end rates can reverse sharply when financial stability replaces inflation as the policy focus.', 'high'),
  ('a42f5378-6e36-5161-976f-2411fe72da40', 'CAT-08', 'shipping_disruption', '2021-03-23', 'Ever Given blocks Suez', ARRAY['GLOBAL'], '{"balance_commerciale":{"direction":-1,"magnitude":0.65,"delay_days":0},"inflation_headline":{"direction":1,"magnitude":0.5,"delay_days":0},"prix_metaux":{"direction":1,"magnitude":0.24,"delay_days":14}}'::jsonb, '{"oil_wti":{"direction":1,"change_pct":4.5,"horizon_days":10},"gas_ttf":{"direction":1,"change_pct":6.1,"horizon_days":10},"metals_industrial":{"direction":1,"change_pct":3.3,"horizon_days":10},"equities_em":{"direction":-1,"change_pct":-2.9,"horizon_days":10}}'::jsonb, 'Shipping bottlenecks feed inflation faster than they hit GDP. | Commodity curves react sooner than broad equity indices.', 'high'),
  ('84433d8b-1681-5b89-b28a-3f90d1a4eccd', 'CAT-08', 'pandemic_supply_shock', '2020-02-23', 'China lockdown supply shock', ARRAY['CN', 'GLOBAL'], '{"croissance_pib":{"direction":-1,"magnitude":0.98,"delay_days":0},"liquidite_globale":{"direction":-1,"magnitude":0.88,"delay_days":0},"emploi_chomage":{"direction":1,"magnitude":0.66,"delay_days":0},"consommation":{"direction":-1,"magnitude":0.66,"delay_days":0},"sentiment_marche":{"direction":-1,"magnitude":0.66,"delay_days":0},"inflation_headline":{"direction":1,"magnitude":0.442,"delay_days":14}}'::jsonb, '{"oil_wti":{"direction":1,"change_pct":4.5,"horizon_days":10},"gas_ttf":{"direction":1,"change_pct":6.1,"horizon_days":10},"metals_industrial":{"direction":1,"change_pct":3.3,"horizon_days":10},"equities_em":{"direction":-1,"change_pct":-2.9,"horizon_days":10}}'::jsonb, 'Factory shutdowns propagate through inventories, shipping and final goods inflation. | Growth-sensitive commodities underperform after the initial scarcity spike.', 'high'),
  ('b9fa9847-86b1-5e91-b776-8443adca2b1a', 'CAT-09', 'drought_major', '2022-07-20', 'European drought disrupts rivers and crops', ARRAY['EZ', 'GLOBAL'], '{"croissance_pib":{"direction":-1,"magnitude":0.31,"delay_days":60},"inflation_headline":{"direction":1,"magnitude":0.62,"delay_days":14},"balance_commerciale":{"direction":-1,"magnitude":0.34,"delay_days":30}}'::jsonb, '{"gas_ttf":{"direction":1,"change_pct":5.7,"horizon_days":15},"metals_industrial":{"direction":1,"change_pct":2.1,"horizon_days":15},"equities_utilities":{"direction":1,"change_pct":1.6,"horizon_days":15},"bonds_inflation_linked":{"direction":1,"change_pct":0.8,"horizon_days":15}}'::jsonb, 'Climate shocks hit agriculture, logistics and power costs simultaneously. | Inflation linkers and utilities are more resilient than cyclical equities.', 'medium'),
  ('3b3fd670-ac75-5676-bdc6-5806923c8bdd', 'CAT-10', 'tech_export_ban', '2022-10-07', 'US chip export ban on China', ARRAY['US', 'CN', 'GLOBAL'], '{"risque_geopolitique":{"direction":1,"magnitude":0.51,"delay_days":0},"investissement":{"direction":-1,"magnitude":0.33,"delay_days":45},"croissance_pib":{"direction":-1,"magnitude":0.24,"delay_days":270},"balance_commerciale":{"direction":-1,"magnitude":0.42,"delay_days":30}}'::jsonb, '{"equities_em":{"direction":-1,"change_pct":-3.4,"horizon_days":10},"usd_dxy":{"direction":1,"change_pct":0.6,"horizon_days":10},"metals_industrial":{"direction":-1,"change_pct":-2.2,"horizon_days":10},"equities_us_growth":{"direction":-1,"change_pct":-1.5,"horizon_days":10}}'::jsonb, 'Strategic technology controls behave like a blend of trade and geopolitical shocks. | Semiconductor restrictions weaken EM equities before they hit top-line trade data.', 'high')
ON CONFLICT (episode_id) DO UPDATE SET
  cat_id = EXCLUDED.cat_id,
  subtype_id = EXCLUDED.subtype_id,
  episode_date = EXCLUDED.episode_date,
  label = EXCLUDED.label,
  geography = EXCLUDED.geography,
  driver_impacts = EXCLUDED.driver_impacts,
  asset_outcomes = EXCLUDED.asset_outcomes,
  notes = EXCLUDED.notes,
  data_quality = EXCLUDED.data_quality;

INSERT INTO asset_sensitivity (
  asset_id, driver_id, sensitivity, direction, delay, asset_class, asset_label_fr, notes
)
VALUES
  ('bonds_sovereign_us', 'taux_directeurs', 0.950, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'strong / immediate'),
  ('bonds_sovereign_ez', 'taux_directeurs', 0.870, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'strong / immediate'),
  ('bonds_ig', 'taux_directeurs', 0.720, -1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'strong / weeks'),
  ('bonds_hy', 'taux_directeurs', 0.650, -1, '1-4w', 'bonds_corporate', 'Credit high yield', 'moderate / weeks'),
  ('bonds_inflation_linked', 'taux_directeurs', 0.320, -1, 'immediate', 'bonds_sovereign', 'Obligations indexees inflation', 'low / immediate'),
  ('equities_us_growth', 'taux_directeurs', 0.860, -1, 'immediate', 'equities', 'Actions US growth', 'strong / immediate'),
  ('equities_us_value', 'taux_directeurs', 0.480, -1, '1-4w', 'equities', 'Actions US value', 'moderate / weeks'),
  ('equities_banks', 'taux_directeurs', 0.440, 1, '1-4w', 'equities', 'Actions bancaires', 'moderate / weeks'),
  ('equities_energy', 'taux_directeurs', 0.210, -1, '1-4w', 'equities', 'Actions energie', 'low / weeks'),
  ('equities_utilities', 'taux_directeurs', 0.580, -1, '1-4w', 'equities', 'Actions utilities', 'moderate / weeks'),
  ('equities_em', 'taux_directeurs', 0.550, -1, '1-4w', 'equities', 'Actions emergentes', 'moderate / weeks'),
  ('usd_dxy', 'taux_directeurs', 0.680, 1, 'immediate', 'fx', 'Dollar DXY', 'strong / immediate'),
  ('eur_usd', 'taux_directeurs', 0.580, -1, 'immediate', 'fx', 'EUR/USD', 'moderate / immediate'),
  ('jpy_usd', 'taux_directeurs', 0.410, -1, 'immediate', 'fx', 'JPY/USD', 'moderate / immediate'),
  ('em_fx', 'taux_directeurs', 0.640, -1, '1-4w', 'fx', 'Devises emergentes', 'moderate / weeks'),
  ('gold', 'taux_directeurs', 0.520, -1, 'immediate', 'commodities', 'Or', 'moderate / immediate'),
  ('oil_wti', 'taux_directeurs', 0.170, -1, '1-6m', 'commodities', 'WTI', 'low / months'),
  ('gas_ttf', 'taux_directeurs', 0.110, -1, '1-6m', 'commodities', 'Gaz TTF', 'low / months'),
  ('metals_industrial', 'taux_directeurs', 0.280, -1, '1-6m', 'commodities', 'Metaux industriels', 'low / months'),
  ('reits', 'taux_directeurs', 0.820, -1, '1-4w', 'real_estate', 'REITs', 'strong / weeks'),
  ('bonds_sovereign_us', 'liquidite_globale', 0.430, 1, '1-4w', 'bonds_sovereign', 'Obligations souveraines US', 'moderate / weeks'),
  ('bonds_sovereign_ez', 'liquidite_globale', 0.360, 1, '1-4w', 'bonds_sovereign', 'Obligations souveraines zone euro', 'moderate / weeks'),
  ('bonds_ig', 'liquidite_globale', 0.504, 1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'moderate / weeks'),
  ('bonds_hy', 'liquidite_globale', 0.666, 1, '1-4w', 'bonds_corporate', 'Credit high yield', 'moderate / weeks'),
  ('bonds_inflation_linked', 'liquidite_globale', 0.162, 1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'low / weeks'),
  ('equities_us_growth', 'liquidite_globale', 0.729, 1, 'immediate', 'equities', 'Actions US growth', 'strong / immediate'),
  ('equities_us_value', 'liquidite_globale', 0.621, 1, 'immediate', 'equities', 'Actions US value', 'moderate / immediate'),
  ('equities_banks', 'liquidite_globale', 0.648, 1, '1-4w', 'equities', 'Actions bancaires', 'moderate / weeks'),
  ('equities_energy', 'liquidite_globale', 0.414, 1, '1-4w', 'equities', 'Actions energie', 'moderate / weeks'),
  ('equities_utilities', 'liquidite_globale', 0.198, 1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'liquidite_globale', 0.702, 1, '1-4w', 'equities', 'Actions emergentes', 'strong / weeks'),
  ('usd_dxy', 'liquidite_globale', 0.510, -1, 'immediate', 'fx', 'Dollar DXY', 'moderate / immediate'),
  ('eur_usd', 'liquidite_globale', 0.306, 1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'liquidite_globale', 0.261, 1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'liquidite_globale', 0.639, 1, '1-4w', 'fx', 'Devises emergentes', 'moderate / weeks'),
  ('gold', 'liquidite_globale', 0.280, 1, 'immediate', 'commodities', 'Or', 'low / immediate'),
  ('oil_wti', 'liquidite_globale', 0.333, 1, '1-4w', 'commodities', 'WTI', 'low / weeks'),
  ('gas_ttf', 'liquidite_globale', 0.144, 1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'liquidite_globale', 0.567, 1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'liquidite_globale', 0.558, 1, '1-4w', 'real_estate', 'REITs', 'moderate / weeks'),
  ('bonds_sovereign_us', 'conditions_credit', 0.240, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines US', 'low / weeks'),
  ('bonds_sovereign_ez', 'conditions_credit', 0.180, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines zone euro', 'low / weeks'),
  ('bonds_ig', 'conditions_credit', 0.730, 1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'strong / weeks'),
  ('bonds_hy', 'conditions_credit', 0.870, 1, '1-4w', 'bonds_corporate', 'Credit high yield', 'strong / weeks'),
  ('bonds_inflation_linked', 'conditions_credit', 0.151, 1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'low / weeks'),
  ('equities_us_growth', 'conditions_credit', 0.680, 1, 'immediate', 'equities', 'Actions US growth', 'strong / immediate'),
  ('equities_us_value', 'conditions_credit', 0.580, 1, 'immediate', 'equities', 'Actions US value', 'moderate / immediate'),
  ('equities_banks', 'conditions_credit', 0.605, 1, '1-4w', 'equities', 'Actions bancaires', 'moderate / weeks'),
  ('equities_energy', 'conditions_credit', 0.386, 1, '1-4w', 'equities', 'Actions energie', 'moderate / weeks'),
  ('equities_utilities', 'conditions_credit', 0.185, 1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'conditions_credit', 0.655, 1, '1-4w', 'equities', 'Actions emergentes', 'moderate / weeks'),
  ('usd_dxy', 'conditions_credit', 0.353, -1, 'immediate', 'fx', 'Dollar DXY', 'moderate / immediate'),
  ('eur_usd', 'conditions_credit', 0.286, 1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'conditions_credit', 0.244, 1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'conditions_credit', 0.596, 1, '1-4w', 'fx', 'Devises emergentes', 'moderate / weeks'),
  ('gold', 'conditions_credit', 0.202, -1, 'immediate', 'commodities', 'Or', 'low / immediate'),
  ('oil_wti', 'conditions_credit', 0.311, 1, '1-4w', 'commodities', 'WTI', 'low / weeks'),
  ('gas_ttf', 'conditions_credit', 0.134, 1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'conditions_credit', 0.529, 1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'conditions_credit', 0.710, 1, '1-4w', 'real_estate', 'REITs', 'strong / weeks'),
  ('bonds_sovereign_us', 'spreads_credit', 0.540, 1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'moderate / immediate'),
  ('bonds_sovereign_ez', 'spreads_credit', 0.360, 1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'moderate / immediate'),
  ('bonds_ig', 'spreads_credit', 0.820, -1, 'immediate', 'bonds_corporate', 'Credit investment grade', 'strong / immediate'),
  ('bonds_hy', 'spreads_credit', 0.930, -1, 'immediate', 'bonds_corporate', 'Credit high yield', 'strong / immediate'),
  ('bonds_inflation_linked', 'spreads_credit', 0.120, -1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'low / weeks'),
  ('equities_us_growth', 'spreads_credit', 0.710, -1, 'immediate', 'equities', 'Actions US growth', 'strong / immediate'),
  ('equities_us_value', 'spreads_credit', 0.630, -1, 'immediate', 'equities', 'Actions US value', 'moderate / immediate'),
  ('equities_banks', 'spreads_credit', 0.860, -1, 'immediate', 'equities', 'Actions bancaires', 'strong / immediate'),
  ('equities_energy', 'spreads_credit', 0.410, -1, '1-4w', 'equities', 'Actions energie', 'moderate / weeks'),
  ('equities_utilities', 'spreads_credit', 0.270, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'spreads_credit', 0.760, -1, 'immediate', 'equities', 'Actions emergentes', 'strong / immediate'),
  ('usd_dxy', 'spreads_credit', 0.440, 1, 'immediate', 'fx', 'Dollar DXY', 'moderate / immediate'),
  ('eur_usd', 'spreads_credit', 0.290, -1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'spreads_credit', 0.360, -1, 'immediate', 'fx', 'JPY/USD', 'moderate / immediate'),
  ('em_fx', 'spreads_credit', 0.830, -1, 'immediate', 'fx', 'Devises emergentes', 'strong / immediate'),
  ('gold', 'spreads_credit', 0.410, 1, 'immediate', 'commodities', 'Or', 'moderate / immediate'),
  ('oil_wti', 'spreads_credit', 0.360, -1, '1-4w', 'commodities', 'WTI', 'moderate / weeks'),
  ('gas_ttf', 'spreads_credit', 0.140, -1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'spreads_credit', 0.580, -1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'spreads_credit', 0.740, -1, '1-4w', 'real_estate', 'REITs', 'strong / weeks'),
  ('bonds_sovereign_us', 'spreads_souverains', 0.210, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'low / immediate'),
  ('bonds_sovereign_ez', 'spreads_souverains', 0.830, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'strong / immediate'),
  ('bonds_ig', 'spreads_souverains', 0.560, -1, 'immediate', 'bonds_corporate', 'Credit investment grade', 'moderate / immediate'),
  ('bonds_hy', 'spreads_souverains', 0.640, -1, 'immediate', 'bonds_corporate', 'Credit high yield', 'moderate / immediate'),
  ('bonds_inflation_linked', 'spreads_souverains', 0.220, -1, 'immediate', 'bonds_sovereign', 'Obligations indexees inflation', 'low / immediate'),
  ('equities_us_growth', 'spreads_souverains', 0.310, -1, 'immediate', 'equities', 'Actions US growth', 'low / immediate'),
  ('equities_us_value', 'spreads_souverains', 0.410, -1, 'immediate', 'equities', 'Actions US value', 'moderate / immediate'),
  ('equities_banks', 'spreads_souverains', 0.720, -1, 'immediate', 'equities', 'Actions bancaires', 'strong / immediate'),
  ('equities_energy', 'spreads_souverains', 0.170, -1, '1-4w', 'equities', 'Actions energie', 'low / weeks'),
  ('equities_utilities', 'spreads_souverains', 0.260, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'spreads_souverains', 0.580, -1, 'immediate', 'equities', 'Actions emergentes', 'moderate / immediate'),
  ('usd_dxy', 'spreads_souverains', 0.390, 1, 'immediate', 'fx', 'Dollar DXY', 'moderate / immediate'),
  ('eur_usd', 'spreads_souverains', 0.420, -1, 'immediate', 'fx', 'EUR/USD', 'moderate / immediate'),
  ('jpy_usd', 'spreads_souverains', 0.310, -1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'spreads_souverains', 0.630, -1, 'immediate', 'fx', 'Devises emergentes', 'moderate / immediate'),
  ('gold', 'spreads_souverains', 0.280, 1, 'immediate', 'commodities', 'Or', 'low / immediate'),
  ('oil_wti', 'spreads_souverains', 0.090, -1, '1-4w', 'commodities', 'WTI', 'low / weeks'),
  ('gas_ttf', 'spreads_souverains', 0.040, -1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'spreads_souverains', 0.290, -1, '1-4w', 'commodities', 'Metaux industriels', 'low / weeks'),
  ('reits', 'spreads_souverains', 0.460, -1, '1-4w', 'real_estate', 'REITs', 'moderate / weeks'),
  ('bonds_sovereign_us', 'inflation_headline', 0.820, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'strong / immediate'),
  ('bonds_sovereign_ez', 'inflation_headline', 0.710, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'strong / immediate'),
  ('bonds_ig', 'inflation_headline', 0.540, -1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'moderate / weeks'),
  ('bonds_hy', 'inflation_headline', 0.340, -1, '1-4w', 'bonds_corporate', 'Credit high yield', 'moderate / weeks'),
  ('bonds_inflation_linked', 'inflation_headline', 0.840, 1, 'immediate', 'bonds_sovereign', 'Obligations indexees inflation', 'strong / immediate'),
  ('equities_us_growth', 'inflation_headline', 0.660, -1, '1-4w', 'equities', 'Actions US growth', 'moderate / weeks'),
  ('equities_us_value', 'inflation_headline', 0.220, 1, '1-4w', 'equities', 'Actions US value', 'low / weeks'),
  ('equities_banks', 'inflation_headline', 0.310, 1, '1-4w', 'equities', 'Actions bancaires', 'low / weeks'),
  ('equities_energy', 'inflation_headline', 0.720, 1, 'immediate', 'equities', 'Actions energie', 'strong / immediate'),
  ('equities_utilities', 'inflation_headline', 0.240, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'inflation_headline', 0.280, -1, '1-4w', 'equities', 'Actions emergentes', 'low / weeks'),
  ('usd_dxy', 'inflation_headline', 0.280, 1, 'immediate', 'fx', 'Dollar DXY', 'low / immediate'),
  ('eur_usd', 'inflation_headline', 0.180, -1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'inflation_headline', 0.160, -1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'inflation_headline', 0.340, -1, '1-4w', 'fx', 'Devises emergentes', 'moderate / weeks'),
  ('gold', 'inflation_headline', 0.630, 1, 'immediate', 'commodities', 'Or', 'moderate / immediate'),
  ('oil_wti', 'inflation_headline', 0.810, 1, 'immediate', 'commodities', 'WTI', 'strong / immediate'),
  ('gas_ttf', 'inflation_headline', 0.720, 1, 'immediate', 'commodities', 'Gaz TTF', 'strong / immediate'),
  ('metals_industrial', 'inflation_headline', 0.460, 1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'inflation_headline', 0.420, -1, '1-4w', 'real_estate', 'REITs', 'moderate / weeks'),
  ('bonds_sovereign_us', 'inflation_core', 0.722, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'strong / immediate'),
  ('bonds_sovereign_ez', 'inflation_core', 0.625, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'moderate / immediate'),
  ('bonds_ig', 'inflation_core', 0.475, -1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'moderate / weeks'),
  ('bonds_hy', 'inflation_core', 0.299, -1, '1-4w', 'bonds_corporate', 'Credit high yield', 'low / weeks'),
  ('bonds_inflation_linked', 'inflation_core', 0.739, 1, 'immediate', 'bonds_sovereign', 'Obligations indexees inflation', 'strong / immediate'),
  ('equities_us_growth', 'inflation_core', 0.740, -1, '1-4w', 'equities', 'Actions US growth', 'strong / weeks'),
  ('equities_us_value', 'inflation_core', 0.194, 1, '1-4w', 'equities', 'Actions US value', 'low / weeks'),
  ('equities_banks', 'inflation_core', 0.370, 1, '1-4w', 'equities', 'Actions bancaires', 'moderate / weeks'),
  ('equities_energy', 'inflation_core', 0.634, 1, 'immediate', 'equities', 'Actions energie', 'moderate / immediate'),
  ('equities_utilities', 'inflation_core', 0.211, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'inflation_core', 0.246, -1, '1-4w', 'equities', 'Actions emergentes', 'low / weeks'),
  ('usd_dxy', 'inflation_core', 0.246, 1, 'immediate', 'fx', 'Dollar DXY', 'low / immediate'),
  ('eur_usd', 'inflation_core', 0.158, -1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'inflation_core', 0.141, -1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'inflation_core', 0.299, -1, '1-4w', 'fx', 'Devises emergentes', 'low / weeks'),
  ('gold', 'inflation_core', 0.554, 1, 'immediate', 'commodities', 'Or', 'moderate / immediate'),
  ('oil_wti', 'inflation_core', 0.520, 1, '1-4w', 'commodities', 'WTI', 'moderate / weeks'),
  ('gas_ttf', 'inflation_core', 0.470, 1, '1-4w', 'commodities', 'Gaz TTF', 'moderate / weeks'),
  ('metals_industrial', 'inflation_core', 0.405, 1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'inflation_core', 0.370, -1, '1-4w', 'real_estate', 'REITs', 'moderate / weeks'),
  ('bonds_sovereign_us', 'anticipations_inflation', 0.640, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'moderate / immediate'),
  ('bonds_sovereign_ez', 'anticipations_inflation', 0.554, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'moderate / immediate'),
  ('bonds_ig', 'anticipations_inflation', 0.421, -1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'moderate / weeks'),
  ('bonds_hy', 'anticipations_inflation', 0.265, -1, '1-4w', 'bonds_corporate', 'Credit high yield', 'low / weeks'),
  ('bonds_inflation_linked', 'anticipations_inflation', 0.790, 1, 'immediate', 'bonds_sovereign', 'Obligations indexees inflation', 'strong / immediate'),
  ('equities_us_growth', 'anticipations_inflation', 0.515, -1, '1-4w', 'equities', 'Actions US growth', 'moderate / weeks'),
  ('equities_us_value', 'anticipations_inflation', 0.172, 1, '1-4w', 'equities', 'Actions US value', 'low / weeks'),
  ('equities_banks', 'anticipations_inflation', 0.242, 1, '1-4w', 'equities', 'Actions bancaires', 'low / weeks'),
  ('equities_energy', 'anticipations_inflation', 0.520, 1, '1-4w', 'equities', 'Actions energie', 'moderate / weeks'),
  ('equities_utilities', 'anticipations_inflation', 0.187, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'anticipations_inflation', 0.218, -1, '1-4w', 'equities', 'Actions emergentes', 'low / weeks'),
  ('usd_dxy', 'anticipations_inflation', 0.218, 1, 'immediate', 'fx', 'Dollar DXY', 'low / immediate'),
  ('eur_usd', 'anticipations_inflation', 0.140, -1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'anticipations_inflation', 0.125, -1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'anticipations_inflation', 0.265, -1, '1-4w', 'fx', 'Devises emergentes', 'low / weeks'),
  ('gold', 'anticipations_inflation', 0.720, 1, 'immediate', 'commodities', 'Or', 'strong / immediate'),
  ('oil_wti', 'anticipations_inflation', 0.632, 1, 'immediate', 'commodities', 'WTI', 'moderate / immediate'),
  ('gas_ttf', 'anticipations_inflation', 0.562, 1, 'immediate', 'commodities', 'Gaz TTF', 'moderate / immediate'),
  ('metals_industrial', 'anticipations_inflation', 0.359, 1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'anticipations_inflation', 0.328, -1, '1-4w', 'real_estate', 'REITs', 'low / weeks'),
  ('bonds_sovereign_us', 'croissance_pib', 0.580, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines US', 'moderate / weeks'),
  ('bonds_sovereign_ez', 'croissance_pib', 0.470, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines zone euro', 'moderate / weeks'),
  ('bonds_ig', 'croissance_pib', 0.310, 1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'low / weeks'),
  ('bonds_hy', 'croissance_pib', 0.630, 1, '1-4w', 'bonds_corporate', 'Credit high yield', 'moderate / weeks'),
  ('bonds_inflation_linked', 'croissance_pib', 0.370, 1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'moderate / weeks'),
  ('equities_us_growth', 'croissance_pib', 0.540, 1, 'immediate', 'equities', 'Actions US growth', 'moderate / immediate'),
  ('equities_us_value', 'croissance_pib', 0.730, 1, 'immediate', 'equities', 'Actions US value', 'strong / immediate'),
  ('equities_banks', 'croissance_pib', 0.770, 1, 'immediate', 'equities', 'Actions bancaires', 'strong / immediate'),
  ('equities_energy', 'croissance_pib', 0.590, 1, '1-4w', 'equities', 'Actions energie', 'moderate / weeks'),
  ('equities_utilities', 'croissance_pib', 0.120, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'croissance_pib', 0.690, 1, '1-4w', 'equities', 'Actions emergentes', 'strong / weeks'),
  ('usd_dxy', 'croissance_pib', 0.140, 1, 'immediate', 'fx', 'Dollar DXY', 'low / immediate'),
  ('eur_usd', 'croissance_pib', 0.080, 1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'croissance_pib', 0.180, 1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'croissance_pib', 0.480, 1, '1-4w', 'fx', 'Devises emergentes', 'moderate / weeks'),
  ('gold', 'croissance_pib', 0.190, -1, '1-4w', 'commodities', 'Or', 'low / weeks'),
  ('oil_wti', 'croissance_pib', 0.620, 1, '1-4w', 'commodities', 'WTI', 'moderate / weeks'),
  ('gas_ttf', 'croissance_pib', 0.280, 1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'croissance_pib', 0.780, 1, '1-4w', 'commodities', 'Metaux industriels', 'strong / weeks'),
  ('reits', 'croissance_pib', 0.410, 1, '1-4w', 'real_estate', 'REITs', 'moderate / weeks'),
  ('bonds_sovereign_us', 'usd_strength', 0.260, 1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'low / immediate'),
  ('bonds_sovereign_ez', 'usd_strength', 0.190, -1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'low / immediate'),
  ('bonds_ig', 'usd_strength', 0.180, -1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'low / weeks'),
  ('bonds_hy', 'usd_strength', 0.290, -1, '1-4w', 'bonds_corporate', 'Credit high yield', 'low / weeks'),
  ('bonds_inflation_linked', 'usd_strength', 0.110, -1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'low / weeks'),
  ('equities_us_growth', 'usd_strength', 0.220, -1, '1-4w', 'equities', 'Actions US growth', 'low / weeks'),
  ('equities_us_value', 'usd_strength', 0.090, -1, '1-4w', 'equities', 'Actions US value', 'low / weeks'),
  ('equities_banks', 'usd_strength', 0.060, -1, '1-4w', 'equities', 'Actions bancaires', 'low / weeks'),
  ('equities_energy', 'usd_strength', 0.180, -1, '1-4w', 'equities', 'Actions energie', 'low / weeks'),
  ('equities_utilities', 'usd_strength', 0.040, 1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'usd_strength', 0.660, -1, 'immediate', 'equities', 'Actions emergentes', 'moderate / immediate'),
  ('usd_dxy', 'usd_strength', 0.950, 1, 'immediate', 'fx', 'Dollar DXY', 'strong / immediate'),
  ('eur_usd', 'usd_strength', 0.870, -1, 'immediate', 'fx', 'EUR/USD', 'strong / immediate'),
  ('jpy_usd', 'usd_strength', 0.610, -1, 'immediate', 'fx', 'JPY/USD', 'moderate / immediate'),
  ('em_fx', 'usd_strength', 0.820, -1, 'immediate', 'fx', 'Devises emergentes', 'strong / immediate'),
  ('gold', 'usd_strength', 0.520, -1, 'immediate', 'commodities', 'Or', 'moderate / immediate'),
  ('oil_wti', 'usd_strength', 0.330, -1, '1-4w', 'commodities', 'WTI', 'low / weeks'),
  ('gas_ttf', 'usd_strength', 0.210, -1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'usd_strength', 0.460, -1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'usd_strength', 0.170, -1, '1-4w', 'real_estate', 'REITs', 'low / weeks'),
  ('bonds_sovereign_us', 'prix_petrole', 0.430, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines US', 'moderate / weeks'),
  ('bonds_sovereign_ez', 'prix_petrole', 0.390, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines zone euro', 'moderate / weeks'),
  ('bonds_ig', 'prix_petrole', 0.240, -1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'low / weeks'),
  ('bonds_hy', 'prix_petrole', 0.140, -1, '1-4w', 'bonds_corporate', 'Credit high yield', 'low / weeks'),
  ('bonds_inflation_linked', 'prix_petrole', 0.580, 1, 'immediate', 'bonds_sovereign', 'Obligations indexees inflation', 'moderate / immediate'),
  ('equities_us_growth', 'prix_petrole', 0.310, -1, '1-4w', 'equities', 'Actions US growth', 'low / weeks'),
  ('equities_us_value', 'prix_petrole', 0.180, 1, '1-4w', 'equities', 'Actions US value', 'low / weeks'),
  ('equities_banks', 'prix_petrole', 0.120, 1, '1-4w', 'equities', 'Actions bancaires', 'low / weeks'),
  ('equities_energy', 'prix_petrole', 0.940, 1, 'immediate', 'equities', 'Actions energie', 'strong / immediate'),
  ('equities_utilities', 'prix_petrole', 0.110, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'prix_petrole', 0.070, -1, '1-4w', 'equities', 'Actions emergentes', 'low / weeks'),
  ('usd_dxy', 'prix_petrole', 0.120, 1, 'immediate', 'fx', 'Dollar DXY', 'low / immediate'),
  ('eur_usd', 'prix_petrole', 0.060, -1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'prix_petrole', 0.040, -1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'prix_petrole', 0.190, -1, '1-4w', 'fx', 'Devises emergentes', 'low / weeks'),
  ('gold', 'prix_petrole', 0.290, 1, 'immediate', 'commodities', 'Or', 'low / immediate'),
  ('oil_wti', 'prix_petrole', 0.980, 1, 'immediate', 'commodities', 'WTI', 'strong / immediate'),
  ('gas_ttf', 'prix_petrole', 0.520, 1, 'immediate', 'commodities', 'Gaz TTF', 'moderate / immediate'),
  ('metals_industrial', 'prix_petrole', 0.170, 1, '1-4w', 'commodities', 'Metaux industriels', 'low / weeks'),
  ('reits', 'prix_petrole', 0.230, -1, '1-4w', 'real_estate', 'REITs', 'low / weeks'),
  ('bonds_sovereign_us', 'prix_metaux', 0.170, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines US', 'low / weeks'),
  ('bonds_sovereign_ez', 'prix_metaux', 0.140, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines zone euro', 'low / weeks'),
  ('bonds_ig', 'prix_metaux', 0.090, 1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'low / weeks'),
  ('bonds_hy', 'prix_metaux', 0.230, 1, '1-4w', 'bonds_corporate', 'Credit high yield', 'low / weeks'),
  ('bonds_inflation_linked', 'prix_metaux', 0.240, 1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'low / weeks'),
  ('equities_us_growth', 'prix_metaux', 0.180, 1, '1-4w', 'equities', 'Actions US growth', 'low / weeks'),
  ('equities_us_value', 'prix_metaux', 0.370, 1, '1-4w', 'equities', 'Actions US value', 'moderate / weeks'),
  ('equities_banks', 'prix_metaux', 0.140, 1, '1-4w', 'equities', 'Actions bancaires', 'low / weeks'),
  ('equities_energy', 'prix_metaux', 0.110, 1, '1-4w', 'equities', 'Actions energie', 'low / weeks'),
  ('equities_utilities', 'prix_metaux', 0.060, -1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'prix_metaux', 0.420, 1, '1-4w', 'equities', 'Actions emergentes', 'moderate / weeks'),
  ('usd_dxy', 'prix_metaux', 0.180, -1, 'immediate', 'fx', 'Dollar DXY', 'low / immediate'),
  ('eur_usd', 'prix_metaux', 0.090, 1, 'immediate', 'fx', 'EUR/USD', 'low / immediate'),
  ('jpy_usd', 'prix_metaux', 0.040, 1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'prix_metaux', 0.210, 1, '1-4w', 'fx', 'Devises emergentes', 'low / weeks'),
  ('gold', 'prix_metaux', 0.160, 1, '1-4w', 'commodities', 'Or', 'low / weeks'),
  ('oil_wti', 'prix_metaux', 0.120, 1, '1-4w', 'commodities', 'WTI', 'low / weeks'),
  ('gas_ttf', 'prix_metaux', 0.090, 1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'prix_metaux', 0.970, 1, 'immediate', 'commodities', 'Metaux industriels', 'strong / immediate'),
  ('reits', 'prix_metaux', 0.130, 1, '1-4w', 'real_estate', 'REITs', 'low / weeks'),
  ('bonds_sovereign_us', 'sentiment_marche', 0.380, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines US', 'moderate / weeks'),
  ('bonds_sovereign_ez', 'sentiment_marche', 0.310, -1, '1-4w', 'bonds_sovereign', 'Obligations souveraines zone euro', 'low / weeks'),
  ('bonds_ig', 'sentiment_marche', 0.560, 1, '1-4w', 'bonds_corporate', 'Credit investment grade', 'moderate / weeks'),
  ('bonds_hy', 'sentiment_marche', 0.740, 1, '1-4w', 'bonds_corporate', 'Credit high yield', 'strong / weeks'),
  ('bonds_inflation_linked', 'sentiment_marche', 0.180, 1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'low / weeks'),
  ('equities_us_growth', 'sentiment_marche', 0.810, 1, 'immediate', 'equities', 'Actions US growth', 'strong / immediate'),
  ('equities_us_value', 'sentiment_marche', 0.690, 1, 'immediate', 'equities', 'Actions US value', 'strong / immediate'),
  ('equities_banks', 'sentiment_marche', 0.720, 1, '1-4w', 'equities', 'Actions bancaires', 'strong / weeks'),
  ('equities_energy', 'sentiment_marche', 0.460, 1, '1-4w', 'equities', 'Actions energie', 'moderate / weeks'),
  ('equities_utilities', 'sentiment_marche', 0.220, 1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'sentiment_marche', 0.780, 1, '1-4w', 'equities', 'Actions emergentes', 'strong / weeks'),
  ('usd_dxy', 'sentiment_marche', 0.420, -1, 'immediate', 'fx', 'Dollar DXY', 'moderate / immediate'),
  ('eur_usd', 'sentiment_marche', 0.340, 1, 'immediate', 'fx', 'EUR/USD', 'moderate / immediate'),
  ('jpy_usd', 'sentiment_marche', 0.290, 1, 'immediate', 'fx', 'JPY/USD', 'low / immediate'),
  ('em_fx', 'sentiment_marche', 0.710, 1, '1-4w', 'fx', 'Devises emergentes', 'strong / weeks'),
  ('gold', 'sentiment_marche', 0.240, -1, 'immediate', 'commodities', 'Or', 'low / immediate'),
  ('oil_wti', 'sentiment_marche', 0.370, 1, '1-4w', 'commodities', 'WTI', 'moderate / weeks'),
  ('gas_ttf', 'sentiment_marche', 0.160, 1, '1-4w', 'commodities', 'Gaz TTF', 'low / weeks'),
  ('metals_industrial', 'sentiment_marche', 0.630, 1, '1-4w', 'commodities', 'Metaux industriels', 'moderate / weeks'),
  ('reits', 'sentiment_marche', 0.620, 1, '1-4w', 'real_estate', 'REITs', 'moderate / weeks'),
  ('bonds_sovereign_us', 'risque_geopolitique', 0.710, 1, 'immediate', 'bonds_sovereign', 'Obligations souveraines US', 'strong / immediate'),
  ('bonds_sovereign_ez', 'risque_geopolitique', 0.340, 1, 'immediate', 'bonds_sovereign', 'Obligations souveraines zone euro', 'moderate / immediate'),
  ('bonds_ig', 'risque_geopolitique', 0.370, -1, 'immediate', 'bonds_corporate', 'Credit investment grade', 'moderate / immediate'),
  ('bonds_hy', 'risque_geopolitique', 0.680, -1, 'immediate', 'bonds_corporate', 'Credit high yield', 'strong / immediate'),
  ('bonds_inflation_linked', 'risque_geopolitique', 0.120, 1, '1-4w', 'bonds_sovereign', 'Obligations indexees inflation', 'low / weeks'),
  ('equities_us_growth', 'risque_geopolitique', 0.550, -1, 'immediate', 'equities', 'Actions US growth', 'moderate / immediate'),
  ('equities_us_value', 'risque_geopolitique', 0.470, -1, 'immediate', 'equities', 'Actions US value', 'moderate / immediate'),
  ('equities_banks', 'risque_geopolitique', 0.730, -1, 'immediate', 'equities', 'Actions bancaires', 'strong / immediate'),
  ('equities_energy', 'risque_geopolitique', 0.640, 1, 'immediate', 'equities', 'Actions energie', 'moderate / immediate'),
  ('equities_utilities', 'risque_geopolitique', 0.080, 1, '1-4w', 'equities', 'Actions utilities', 'low / weeks'),
  ('equities_em', 'risque_geopolitique', 0.820, -1, 'immediate', 'equities', 'Actions emergentes', 'strong / immediate'),
  ('usd_dxy', 'risque_geopolitique', 0.740, 1, 'immediate', 'fx', 'Dollar DXY', 'strong / immediate'),
  ('eur_usd', 'risque_geopolitique', 0.440, -1, 'immediate', 'fx', 'EUR/USD', 'moderate / immediate'),
  ('jpy_usd', 'risque_geopolitique', 0.570, -1, 'immediate', 'fx', 'JPY/USD', 'moderate / immediate'),
  ('em_fx', 'risque_geopolitique', 0.870, -1, 'immediate', 'fx', 'Devises emergentes', 'strong / immediate'),
  ('gold', 'risque_geopolitique', 0.810, 1, 'immediate', 'commodities', 'Or', 'strong / immediate'),
  ('oil_wti', 'risque_geopolitique', 0.690, 1, 'immediate', 'commodities', 'WTI', 'strong / immediate'),
  ('gas_ttf', 'risque_geopolitique', 0.580, 1, 'immediate', 'commodities', 'Gaz TTF', 'moderate / immediate'),
  ('metals_industrial', 'risque_geopolitique', 0.180, -1, '1-4w', 'commodities', 'Metaux industriels', 'low / weeks'),
  ('reits', 'risque_geopolitique', 0.380, -1, '1-4w', 'real_estate', 'REITs', 'moderate / weeks')
ON CONFLICT (asset_id, driver_id) DO UPDATE SET
  sensitivity = EXCLUDED.sensitivity,
  direction = EXCLUDED.direction,
  delay = EXCLUDED.delay,
  asset_class = EXCLUDED.asset_class,
  asset_label_fr = EXCLUDED.asset_label_fr,
  notes = EXCLUDED.notes,
  last_reviewed = CURRENT_DATE;

COMMIT;
